### PR TITLE
Add GitHub Actions - closes #14

### LINKED ISSUE #14: GitHub Actions
GHA is very interesting and I would provide a PR to migrate to it.

Did you already signup to the GHA beta? =)

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR adds the GitHub Actions setup to run the tests there.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Seems there is some issue with bigint-fix, because it is cloned using ssh maybe: https://github.com/DanielRuf/sodium-plus/commit/3328b0bedb38e57f0b7740a8b47a63e37324ccc1/checks?check_suite_id=266312379#step:4:6

**Comment by DanielRuf** [comment]
Seems there is some issue with bigint-fix, because the branch is not there anymore: https://github.com/DanielRuf/sodium-plus/commit/3328b0bedb38e57f0b7740a8b47a63e37324ccc1/checks?check_suite_id=266312379#step:4:6

In general it is best to use a released version instead of using the Git endpoint.

**Comment by DanielRuf** [comment]
Works now: https://github.com/DanielRuf/sodium-plus/runs/261297958

**Comment by paragonie-scott** [comment]
Uh, yeah. See https://github.com/paragonie/sodium-plus/issues/17 we're waiting on a libsodium-wrappers release.

**Comment by paragonie-scott** [comment]
Thanks @DanielRuf 👍

**Pull request merged**
